sudo: required

services:
  - docker

language: node_js

node_js:
  - "10.15.0"

before_install:
  - docker build -t beaubouchard/jasonquestion .
script:
  - docker run beaubouchard/jasonquestion npm run test
